name: 'Deploy OpenTelemetry'

on:
  push:
    branches: main
    paths:
      - .github/workflows/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: otel-deploy-job
    steps:
      - uses: /actions/instrument/job@v5.35.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.ACTIONS_GITHUB_TOKEN  }}","${{ secrets.PARENT_DOMAIN }}"]'
      - uses: /actions/instrument/deploy@v5.35.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics'
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs'
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: 'http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces'
        with:
          github_token: '${{ secrets.ACTIONS_GITHUB_TOKEN  }}'
    permissions:
      actions: read
