
name: OpenTelemetry
on:
  check_suite:
    types:
      - completed
jobs:
  export:
    if: github.event.check_suite.app.slug != 'github-actions'
    runs-on: ubuntu-latest
    permissions:
      checks: read
      actions: read
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/checksuite@v5.41.0
        env:
          OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/metrics
          OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/logs
          OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://${{ secrets.PARENT_DOMAIN }}:4318/v1/traces
    container: ghcr.io/plengauer/opentelemetry-github-workflow-instrumentation-runner:v5.42.0
